// <auto-generated />
namespace dip2.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<AddressBookModel.AddressBookContext>)>]
type AddressBookContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.7")
            |> ignore

        modelBuilder.Entity("AddressBookModel+AddressBook", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .UseIdentityByDefaultColumn() |> ignore
            b.Property<string>("Email")
                .HasColumnType("text") |> ignore
            b.Property<string>("Name")
                .HasColumnType("text") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("AddressBook") |> ignore

        )) |> ignore

